// Mocks generated by Mockito 5.4.6 from annotations
// in customfit_ai_flutter_sdk/test/unit/core/error/config_recovery_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:customfit_ai_flutter_sdk/src/analytics/summary/summary_manager.dart'
    as _i6;
import 'package:customfit_ai_flutter_sdk/src/client/managers/config_manager.dart'
    as _i2;
import 'package:customfit_ai_flutter_sdk/src/config/core/cf_config.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ConfigManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigManager extends _i1.Mock implements _i2.ConfigManager {
  MockConfigManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String getString(
    String? key,
    String? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getString,
          [
            key,
            defaultValue,
          ],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getString,
            [
              key,
              defaultValue,
            ],
          ),
        ),
      ) as String);

  @override
  bool getBoolean(
    String? key,
    bool? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBoolean,
          [
            key,
            defaultValue,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  num getNumber(
    String? key,
    num? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNumber,
          [
            key,
            defaultValue,
          ],
        ),
        returnValue: 0,
      ) as num);

  @override
  Map<String, dynamic> getJson(
    String? key,
    Map<String, dynamic>? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJson,
          [
            key,
            defaultValue,
          ],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  T getConfigValue<T>(
    String? key,
    T? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConfigValue,
          [
            key,
            defaultValue,
          ],
        ),
        returnValue: _i3.dummyValue<T>(
          this,
          Invocation.method(
            #getConfigValue,
            [
              key,
              defaultValue,
            ],
          ),
        ),
      ) as T);

  @override
  void addConfigListener<T>(
    String? key,
    void Function(T)? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addConfigListener,
          [
            key,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeConfigListener<T>(
    String? key,
    void Function(T)? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeConfigListener,
          [
            key,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearConfigListeners(String? key) => super.noSuchMethod(
        Invocation.method(
          #clearConfigListeners,
          [key],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getAllFlags() => (super.noSuchMethod(
        Invocation.method(
          #getAllFlags,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, dynamic>? getFullFlagConfig(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getFullFlagConfig,
        [key],
      )) as Map<String, dynamic>?);

  @override
  bool hasConfiguration() => (super.noSuchMethod(
        Invocation.method(
          #hasConfiguration,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void shutdown() => super.noSuchMethod(
        Invocation.method(
          #shutdown,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<bool> refreshConfigs() => (super.noSuchMethod(
        Invocation.method(
          #refreshConfigs,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void dumpConfigMap() => super.noSuchMethod(
        Invocation.method(
          #dumpConfigMap,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isSdkFunctionalityEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isSdkFunctionalityEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void updateConfigsFromClient(Map<String, dynamic>? newConfigs) =>
      super.noSuchMethod(
        Invocation.method(
          #updateConfigsFromClient,
          [newConfigs],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> waitForInitialLoad() => (super.noSuchMethod(
        Invocation.method(
          #waitForInitialLoad,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void setupListeners({
    required void Function(_i5.CFConfig)? onConfigChange,
    required _i6.SummaryManager? summaryManager,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setupListeners,
          [],
          {
            #onConfigChange: onConfigChange,
            #summaryManager: summaryManager,
          },
        ),
        returnValueForMissingStub: null,
      );
}
