name: customfit_ai_flutter_sdk
description: A comprehensive Flutter SDK for CustomFit.ai's feature flagging, A/B testing, and analytics platform. Provides real-time configuration updates, offline support, type-safe APIs, and cross-platform compatibility for iOS, Android, Web, and Desktop applications.
version: 0.1.0
homepage: https://customfit.ai
repository: https://github.com/customfit-ai-tech/customfit-ai-flutter-sdk
issue_tracker: https://github.com/customfit-ai-tech/customfit-ai-flutter-sdk/issues
documentation: https://doc.customfit.ai

topics:
  - feature-flags
  - ab-testing
  - analytics
  - configuration
  - remote-config

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.0
  dio: ^5.8.0
  battery_plus: ^6.2.2
  device_info_plus: ^11.5.0
  connectivity_plus: ^6.1.4
  synchronized: ^3.3.1
  path_provider: ^2.1.5
  # Security-related dependencies for open source readiness
  dart_jsonwebtoken: ^3.2.0
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.6

  meta: ^1.16.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.8.0
  mockito: ^5.4.5
  args: ^2.6.0
  yaml: ^3.1.2
  path: ^1.9.1
  fake_async: ^1.3.1
  path_provider_platform_interface: ^2.1.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
