// Mocks generated by Mockito 5.4.6 from annotations
// in customfit_ai_flutter_sdk/test/unit/client/managers/listener_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:customfit_ai_flutter_sdk/src/client/listener/all_flags_listener.dart'
    as _i3;
import 'package:customfit_ai_flutter_sdk/src/client/listener/feature_flag_change_listener.dart'
    as _i2;
import 'package:customfit_ai_flutter_sdk/src/network/connection/connection_information.dart'
    as _i6;
import 'package:customfit_ai_flutter_sdk/src/network/connection/connection_manager.dart'
    as _i4;
import 'package:customfit_ai_flutter_sdk/src/network/connection/connection_status.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FeatureFlagChangeListener].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeatureFlagChangeListener extends _i1.Mock
    implements _i2.FeatureFlagChangeListener {
  MockFeatureFlagChangeListener() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void onFeatureFlagChanged(
    String? flagKey,
    dynamic oldValue,
    dynamic newValue,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onFeatureFlagChanged,
          [
            flagKey,
            oldValue,
            newValue,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AllFlagsListener].
///
/// See the documentation for Mockito's code generation for more information.
class MockAllFlagsListener extends _i1.Mock implements _i3.AllFlagsListener {
  MockAllFlagsListener() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void onAllFlagsChanged(
    Map<String, dynamic>? oldFlags,
    Map<String, dynamic>? newFlags,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onAllFlagsChanged,
          [
            oldFlags,
            newFlags,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ConnectionStatusListener].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionStatusListener extends _i1.Mock
    implements _i4.ConnectionStatusListener {
  MockConnectionStatusListener() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void onConnectionStatusChanged(
    _i5.ConnectionStatus? newStatus,
    _i6.ConnectionInformation? info,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onConnectionStatusChanged,
          [
            newStatus,
            info,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
